ALTER TABLE projects ADD COLUMN IF NOT EXISTS vat_percent     NUMERIC(5,2) NOT NULL DEFAULT 7;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS overhead_percent NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS show_overhead    BOOLEAN      NOT NULL DEFAULT true;
